/*
 * Basic tree that stores a value.
*/
var Tree = function (value) {
  this.value = value;
  this.children = [];
};

Tree.prototype.map = function (callback, copyTree) {
  // TODO: return a new tree with the same structure as `this`,
  //       with values generated by the callback
  var copyTree = new Tree(callback(this.value));
  //base case - if no children, return copy of tree with original tree's value
  if (this.children.length === 0){
    return copyTree;
  }
  //recursive case - if there are children, iterate through the children of original tree, recursively calling map on each child, and adding child to copy tree

  for (var i = 0; i < this.children.length; i ++) {
    copyTree.addChild(this.children[i].map(callback, copyTree));
  }

  return copyTree;
};

/**
 * You shouldn't need to change anything below here,
 * but feel free to read it.
 */

/**
  * add an immediate child
  * (wrap values in Tree nodes if they're not already)
  */
Tree.prototype.addChild = function (child) {
  if (! child ||  ! (child instanceof Tree)){
    child = new Tree(child);
  }

  if (! this.isDescendant(child)) {
    this.children.push(child);
  } else {
    throw new Error("That child is already a child of this tree");
  }
  // return the new child node for convenience
  return child;
};

/**
  * check to see if the provided tree is already a child of this
  * tree __or any of its sub trees__
  */
Tree.prototype.isDescendant = function (child) {
  if (this.children.indexOf(child) !== -1) {
    // `child` is an immediate child of this tree
    return true;
  } else {
    for (var i = 0; i < this.children.length; i++) {
      if(this.children[i].isDescendant(child)){
        // `child` is descendant of this tree
        return true;
      }
    }
    return false;
  }
};

/**
  * remove an immediate child
  */
Tree.prototype.removeChild = function (child) {
  var index = this.children.indexOf(child);
  if (index !== -1) {
    // remove the child
    this.children.splice(index,1);
  } else {
    throw new Error("That node is not an immediate child of this tree");
  }
};

var tree = new Tree (5);
var branch = new Tree (3);
var twig = new Tree (2);
var otherBranch = new Tree (4);
tree.addChild(branch);
tree.addChild(otherBranch);
branch.addChild(twig);
